### ISSUE TITLE
Exception calling "BulkWalk" with "11" argument(s): "Value cannot be null.

### ISSUE THREAD

**Issue by icmtf** [lahell/SNMPv3#5]
```
PS C:\Users\me\Desktop>> $WalkRequest = @{
    UserName   = 'myuser
    Target     = '10.52.42.15'
    OID        = '1.3.6.1.2.1.1'
    AuthType   = 'SHA1'
    AuthSecret = 'abcdefg
    PrivType   = 'AES128'
    PrivSecret = 'hijklmnop'
}

Invoke-SNMPv3Walk @WalkRequest
Exception calling "GetResponse" with "2" argument(s): "Request timed out after 3000-ms."
At C:\Program Files\WindowsPowerShell\Modules\SNMPv3\1.1.2\Public\Invoke-SNMPv3Walk.ps1:135 char:5
+     $Report = $Discovery.GetResponse($Timeout, $IPEndPoint)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TimeoutException
 
Exception calling "BulkWalk" with "11" argument(s): "Value cannot be null.
Parameter name: report"
At C:\Program Files\WindowsPowerShell\Modules\SNMPv3\1.1.2\Public\Invoke-SNMPv3Walk.ps1:139 char:5
+     [Lextm.SharpSnmpLib.Messaging.Messenger]::BulkWalk(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException
```

Whatever I do. Either walk or get the same "bulk" error appears.

**Comment by berny275** [comment]
Request timed out

You're not getting a response from the other side, is there an access list that you can check? Have you checked your config with the Paessler snmp tester?

**Comment by icmtf** [comment]
> Request timed out
> 
> You're not getting a response from the other side, is there an access list that you can check? Have you checked your config with the Paessler snmp tester?

Can't really install anything on this machine.

This machine hosts also monitoring system. Its IP is added to SNMP ACL so I don't think that's the case.
However I'll dig further to see what's going on.

**Comment by berny275** [comment]
I've just taken a copy of the files from "C:\Program Files (x86)\Paessler SNMP Tester" and run them on another server and it works fine, so you could copy the files over and delete them after.

**Comment by aaronaxvig** [comment]
I have been encountering this issue as well, both the GetResponse with 2 arguments and BulkWalk with 11 arguments errors.  I have tested with Paessler SNMP Tester on the system and always get responses in either 250ms or 2100ms, never anything in between, which is a little odd but might be due to inner workings of Paessler SNMP Tester.

This system has quite a few devices being monitored with this PowerShell module and all of the others are working fine, so I suspect this is relevant: I am seeing this only for two SonicWall VPN devices.  I am walking `1.3.6.1.4.1.8741.6` which typically returns about 15 rows of data.

**Comment by lahell** [comment]
`Invoke-SNMPv3Walk` is based on [this sample](https://github.com/lextudio/sharpsnmplib-samples/tree/master/Samples/CSharpCore/snmpwalk). Are any of you able to compile that project and test if you get the same error?

**Comment by berny275** [comment]
https://github.com/lextudio/sharpsnmplib/issues/153

https://github.com/lextudio/sharpsnmplib/issues/155

**Comment by lahell** [comment]
Thanks @berny275.

Are you saying I should set `UseFullRange` to `$false` in all three Invoke-functions before calling `GetNextDiscovery`?

If I understand you correctly I should also use `GetRequestPdu` instead of `GetBulkRequestPdu`. Thats what I did in SNMPv3 1.1.2, the latest version published in PowerShell Gallery. However, I thought that was incorrect because the [snmpwalk sample](https://github.com/lextudio/sharpsnmplib-samples/blob/master/Samples/CSharpCore/snmpwalk/Program.cs#L220) uses `GetBulkRequestPdu`.

Commit aaacd9e7b79d910eb8808ecc40c8b5b3dff47d91 is not in the latest published version. Should it be reverted?

**Comment by lahell** [comment]
@icmtf @aaronaxvig @berny275 
Can you test `Invoke-SNMPv3Walk` with the `-NoFullRange` switch from commit 416d4ea20aae3a449ed56c26c19db5e2c3095295?

**Comment by aaronaxvig** [comment]
That did not seem to resolve the issue.

**Comment by lahell** [comment]
@aaronaxvig Thanks for testing. Did you also test `GetRequestPdu` vs `GetBulkRequestPdu`? Have you tried other snmp-tools? Have you read the following? https://www.sonicwall.com/support/knowledge-base/no-response-snmp-error-2003/170505495768662/

**Comment by lahell** [comment]
Closed because I cannot reproduce this issue.
